### PR TITLE
Remake using jekyll

### PR DESCRIPTION
**Pull request by hellcp**
Using openSUSE Jekyll Theme, makes maintaining the pages easier, since there is less boilerplate, and it still works with GitHub Pages

image

### CODE REVIEW

**Comment by jeffmahoney** [comment]
These pages are automatically generated and updated via git push. Perhaps it would make sense to put the code for generating them in a branch so we can handle pull requests like these.

@hramrach

**Comment by hramrach** [comment]
Trivial style changes can be merged back to the original template. Rewrite using bazillion of unsigned gems cannot be merged because there is no sandbox to run such generator in the kbuild.

**Comment by hramrach** [comment]
In other words if you want to take ownership of the repository and make sure the site is re-generated in response to branches added/removed in the git repository and OBS feel free. Otherwise this PR is unacceptable.

**Comment by hellcp** [comment]
I don't see the issue though, you don't have to install those gems anywhere, you just have to upload the markdown files to this repository, and github pages will build the website for you based on that

**Comment by hellcp** [comment]
@hramrach I assume that means I will get the chance to have a look at the code that currently does this?

**Comment by hramrach** [comment]
> I don't see the issue though, you don't have to install those gems anywhere, you just have to upload the markdown files to this repository, and github pages will build the website for you based on that

That however means we cannot move away from github. The pages as they are are static HTML that can be places anywhere and will just work.

**Comment by hellcp** [comment]
You are very welcome to use openSUSE's jekyll.infra.opensuse.org which renders jekyll pages all around our infrastructure hourly if you don't want to use github.

**Comment by jeffmahoney** [comment]
Given that this is something that *can* be generated anywhere, having github pages do it isn't really a lock-in.

**Comment by hramrach** [comment]
Pushed the generator script into code branch.

**Comment by hramrach** [comment]
@ptesarik ^

**Pull request closed without merging**
